#!/bin/sh

# source all sqg functions
. /usr/libexec/sbopkg/sqg/functions

REPO_DIR="$1"
QUEUEDIR="$2"
INFO="$3"
VERBOSE="${4:-no}"
CUSTOM_QUEUE="${5:-}"

check_validity $INFO

if [ $? -ne 0 ]; then
  echo ""
  echo "Found invalid .info file: $INFO. Skipping."
  echo ""
  continue;
else
  . $INFO

  if [ "$VERBOSE" == "yes" ]; then
    INFO_BASENAME=$(basename $INFO .info)
    echo "Processing $INFO_BASENAME."
  fi

  if [[ ! -z $CUSTOM_QUEUE ]]; then
    build_queuefile "$REPO_DIR" "$QUEUEDIR" "$PRGNAM" "$CUSTOM_QUEUE"
  elif [[ ! -z $REQUIRES ]]; then
    build_queuefile "$REPO_DIR" "$QUEUEDIR" "$PRGNAM"
  fi
fi
