#!/bin/sh

# $Id$

# sqg - sbopkg queuefile generator
# A script designed to generate queuefiles for sbopkg with recursively-listed
# dependencies from the REQUIRES line of the .info files.

# Copyright 2013 Chess Griffin <chess@chessgriffin.com> and
# slakmagik <slakmagik@gmail.com>
# Copyright 2016-2017 Willy Sudiarto Raharjo <willysr@sbopkg.org>

# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright notice,
# this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR
#  IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
#  OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN
#  NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
#  TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
#  PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
#  LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
#  NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
#  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

### OPTIONAL CONFIGURATION BELOW ###

SBOPKG_CONF=${SBOPKG_CONF:-/etc/sbopkg/sbopkg.conf}

# If necessary, override SBOPKG_CONF above or directly from the environment.
# The user may want to change QUEUEDIR to a local temporary directory in $HOME
# since queuefiles in QUEUEDIR will be overwritten by this script. QUEUEDIR
# is commented out on purpose to get the user to review these variables.
# QUEUEDIR must be writable by the user executing the script. SKIP_EMPTY
# means the script will not create queuefiles for packages with an empty
# REQUIRES= line in the .info file. Uncomment or export a value to create
# queuefiles for packages with an empty REQUIRES= line (which will only
# contain the package name in the queuefile since there are no REQUIRES).

#QUEUEDIR=${QUEUEDIR:-/var/lib/sbopkg/queues}
REPO_BRANCH=${REPO_BRANCH:-$(cat /etc/slackware-version | awk '{print $2}')}
#SKIP_EMPTY=${SKIP_EMPTY:-NO}

### NO CHANGES SHOULD BE NECESSARY BELOW THIS LINE ###

# source all sqg functions
. /usr/share/sbopkg/sqg/functions

SCRIPT=${0##*/}

sanity_checks

case $1 in
  -a)
    if [ "$2" == "-j" ] && [ -n $3 ]; then
      get_jobs $3
      JOBS=$?
    fi
    shift;
    execute_build "$REPO_DIR" "$QUEUEDIR" "" "yes" $JOBS ;;
  -p)
    shift;
    execute_build "$REPO_DIR" "$QUEUEDIR" "$@" "no" $JOBS ;;
   *) usage $SCRIPT ;;
esac

echo "Done."
exit 0
