.TH SBOPKG.CONF 5 "May 2009" sbopkg-SVN ""
.SH NAME
.B sbopkg.conf
\- Configuration file for sbopkg

.SH DESCRIPTION

The sbopkg.conf file contains configuration settings for
.B sbopkg
(8), a tool for interacting with the SlackBuilds.org ("SBo")
repository, a collection of third-party SlackBuild scripts to build
Slackware packages.  A sample file is provided at
/etc/sbopkg/sbopkg.conf.new.

The different configuration options are:

.TP 5
.B REPO_NAME
.br
This option allows the user to choose the repository to use.
The default options are SBo, SB64 and local.
The 'local' choice corresponds to a user-maintained repository whose
structure must be the same as the one used by SlackBuilds.org.  NOTE:
all of the REPO_* variables are affected by the repository files
maintained in /etc/sbopkg/repos.d.  Please see the README-repos.d
document in the sbopkg /doc directory.

The default value of REPO_NAME is:
.br
REPO_NAME=${REPO_NAME:-SBo}.

.TP 5
.B REPO_BRANCH
.br
This option allows the user to set the default active repository branch.
The current options are 11.0, 12.0, 12.1 and 12.2 for the SBo repository,
master for the SB64 repositort and local for the local repository.

The default value of REPO_BRANCH is:
.br
REPO_BRANCH=${REPO_BRANCH:-12.2}.

.TP 5
.B REPO_ROOT
.br
This option allows the user to set the location of the local
mirrors of the remote repositories.  Currently, the size of a local copy of
the SBo repository is less than 50MB.

The default value of REPO_ROOT is:
.br
REPO_ROOT=${REPO_ROOT:-/var/lib/sbopkg}.

.TP 5
.B SRCDIR
.br
This option contains the location of the cache directory where
source downloads will be saved.

The default value of SRCDIR is:
.br
SRCDIR=${SRCDIR:-/var/cache/sbopkg}.

.TP 5
.B SBOPKGTMP
.br
This option sets the default directory where certain working
files are saved on a temporary basis.

The default value of SBOPKGTMP is:
.br
SBOPKGTMP=${SBOPKGTMP:-/tmp/sbopkg}.

.TP 5
.B TMP
.br
This option sets the default directory where built packages should be stored.
TMP must be exported as it is used by the SlackBuilds.  Also note that the
default value of TMP is the same as in the SBo SlackBuild scripts.

The default value of TMP is:
.br
export TMP=${TMP:-/tmp/SBo}.

.TP 5
.B OUTPUT
.br
This option sets the default directory where compiled packages are
saved.  OUTPUT must be exported as it is also used by the SBo
SlackBuilds.  Also note that the default value of OUTPUT is therefore
the same as in the SBo SlackBuilds.

The default value of OUTPUT is:
.br
export OUTPUT=${OUTPUT:-/tmp}.

.TP 5
.B ARCH
.br
This option sets the default architecture for compiling packages from
the repository.  ARCH must be exported as it is also used by the SBo
SlackBuilds.  Also note that the default value of ARCH is therefore
the same as in the SBo SlackBuilds.  Generally, this value can be
set to either i486, i686, or x86_64.

The default value of ARCH is:
.br
export ARCH=${ARCH:-i486}.

.TP 5
.B QUEUEDIR
.br
This option defines the directory under which saved queue files will
be kept.

The default value of QUEUEDIR is:
.br
QUEUEDIR=${QUEUEDIR:-/var/lib/sbopkg/queues}.

.TP 5
.B KEEPLOG
.br
This option should be set to YES or NO.  This option allows the user
to choose whether to keep a permanent log of packages that are built
with sbopkg in order to go back and review the build, and any errors,
after exiting sbopkg.  If set to YES, this permanent log is saved at
$LOGDIR/sbopkg-build-log.

The default value of KEEPLOG is: YES.

.TP 5
.B LOGDIR
.br
This option sets the location for the sbopkg permanent log if KEEPLOG
is set to YES (see previous paragraph).

The default value of LOGDIR is:
.br
LOGDIR=${LOGDIR:-/var/log/sbopkg}.

.TP 5
.B DEBUG
.br
This option should be set to 0, 1, or 2.  DEBUG sets the default
debugging level for the update list feature of sbopkg.  When DEBUG is
set to 0, then only potential updated packages are listed.  This was
the default output prior to the DEBUG variable.  When DEBUG is set to
1, then potential updates plus packages not in the repo and packages
that are newer than the repo are listed.  Changing DEBUG to 1 may be
helpful if it appears the updatelist might be missing an update.

The default value of DEBUG is: 0.

.TP 5
.B RSYNCFLAGS
.br
Rsync is used by sbopkg to mirror the SlackBuilds.org repository.
This option allows the user to manually tweak the rsync flags
(options) that are used by sbopkg.  Users are cautioned against making
any changes to the default values since new flags may or may not work.
Note:  the rsync command in sbopkg already uses the --archive,
--delete, --no-owner, and --exclude flags, so there is no need to add
them to the RSYNCFLAGS option.  Changing these default options is not
recommended.

The default value of RSYNCFLAGS is: "--timeout=10 --verbose".

.TP 5
.B WGETFLAGS
.br
Wget is used by sbopkg to download the source files for package
building.  This option allows the user to manually tweak the wget
flags (options) that are used by sbopkg.  Users are cautioned against
making any changes to the default values since new flags may or may
not work.  Note:  the wget command in sbopkg already uses the -O flag,
so there is no need to add that to the WGETFLAGS option.  Changing
these default options is not recommended.

The default value of WGETFLAGS is:
.br
"--continue --progress-bar --timeout=15 --tries=5".

.TP 5
.B DIFF
.br
This option allows the user to set which diff program to use when
sbopkg displays differences between edited files.

The default value of DIFF is:
.br
DIFF=${DIFF:-diff}.

.TP 5
.B DIFFOPTS
.br
This option allows the user to set which options are used by the $DIFF
program when sbopkg displays differences between edited files.

The default value of DIFFOPTS is:

DIFFOPTS=${DIFFOPTS:--u}

.SH FILES
.TP 5
.B /etc/sbopkg/sbopkg.conf

.SH OVERRIDING ENVIRONMENTAL VARIABLES
It is possible to set or override environmental variables and pass
them to the SlackBuild scripts when they are built from within sbopkg.
This is already demonstrated in the following line in the sbopkg.conf
file:

export TMP=${TMP:-/tmp/SBo}

This sets $TMP to /tmp/SBo for building SBo packages within sbopkg (which is
current default for SBo SlackBuilds already).  Since this variable is
exported, it could be changed for both sbopkg and for building SBo
packages within sbopkg.  For example, changing this line so it reads:

export TMP=${TMP:-/home/sbo/tmp}

would then set $TMP to /home/sbo/tmp for building SBo
packages.  OUTPUT can also be changed to save compiled packages in a
location other than the default of /tmp.

You can also export variables in sbopkg.conf that are not used by
sbopkg at all.

.SH "SEE ALSO"
.BR sbopkg (8)
