.\"=====================================================================
.TH SBOPKG.CONF 5 "xxxDATExxx" sbopkg-xxxVERSIONxxx ""
.\"=====================================================================
.SH NOMBRE
sbopkg.conf \- archivo de configuración para sbopkg
.\"=====================================================================
.SH DESCRIPCION
El archivo
.I sbopkg.conf
contiene los ajustes de configuración para
.BR sbopkg (8),
una herramienta para interactuar con el repositorio de SlackBuilds.org ("SBo"), una 
colección de scripts SlackBuild de terceros para construir paquetes para
Slackware.
El archivo de configuración por defecto esta instalado en
.IR /etc/sbopkg/sbopkg.conf .
El usuario puede sobreescribir cualquier configuración creando el archivo
.IR ~/.sbopkg.conf .
.PP
Por favor lea la sección
.B NOTAS
para mas información sobre las variables, incluyendo la sección
.BR ARCH .
.PP
Todas las opciones booleanas necesitan un
.B YES
o un
.B NO
sin tener en cuenta si son mayúsculas o minúsculas.
Todos los valores de la variables que contengan directorios deben ser absolutas.
.PP
Las opciones de configuración por defecto son:
.\"---------------------------------------------------------------------
.TP 3
.B ALLOW_MULTI
Booleano.
.IP
Cuando se establece en
.BR YES ,
esta opcion permite al usuario iniciar varias veces
.B sbopkg
simultaneamente.
.IP
Por favor comprenda que esta opción es provehí­da por comodidad, pero
puede generar un número potencial de problemas que deberá encarar
cuando habilite ésta opción (y no vamos a trabajar con usuarios haciendo
tonterias), debe considerar que ésta es una característica 
EXPERIMENTAL NO SOPORTADA.
Si encuentra problemas, por favor asegúrese que no es causado por 
usted realizando cosas inadecuadas.
.IP
Por ejemplo, algunas de estas cosas, no deberían utilizarse con estas 
opciones activadas:
.RS 5
.TP 3
\(bu
inicia instancias con una mezcla de configuraciones
.B YES
y
.B NO
.TP
\(bu
sincronizar un repositorio, cuando otra instancia lo esta utilizando
.TP
\(bu
cambiar la rama de un repositorio git, cuando otra instancia lo esta usando
(esta advertencia no se utiliza para sincronizar los repositorios)
.TP
\(bu
construir o instalar el mismo paquete a la vez desde diferentes instancias
.TP
\(bu
guardar un archivo de colas mientras se esta usando desde otra instancia
.RE
.IP
Puede haber mas situaciones inseguras de las que nosotros pensamos.
Tenga cuidado.
.IP
La configuración por defecto es:
.IP
\fCALLOW_MULTI=${ALLOW_MULTI:-NO}\fP
.\"---------------------------------------------------------------------
.TP
.B CLEANUP
Booleano.
.IP
Cuando se establece como
.BR YES ,
los archivos fuente desempaquetados y el árbol de paquetes situados en
.I $TMP
son eliminados inmediatamente después de la construcción, tanto el archivo
descargado como el paquete que han sido colocados en
.I $SRCDIR
y
.IR $OUTPUT .
.IP
.IP
Un efecto colateral de configurar
.B CLEANUP
con
.B YES
es que 
.B TMP
esta configurada con su propio directorio temporal, en
.BR sbopkg,
como
.RI ( $TMPDIR/sbopkg.RANDOM_STRING ),
por lo tanto cualquier otro
.B TMP
será ignorado.
.IP
La configuración por defecto es:
.IP
\fCCLEANUP=${CLEANUP:-NO}\fP
.\"---------------------------------------------------------------------
.TP
.B DEBUG_UPDATES
Enumeración.
.IP
Esta opción debe ser establecida como
.BR 0 ,
.BR 1 ,
o
.BR 2 .
.B DEBUG_UPDATES
establece el nivel de depuración (debugging) por defecto para actualizar la lista de 
funciones de
.BR sbopkg .
Cuando esta establecido en
.BR 0 ,
solo las actualizaciones importantes (o reducciones de version) de 
paquetes son listados.
Cuando esta establecido en
.BR 1 ,
se listan actualizaciones importantes mas los paquetes que no están en el repositorio y 
paquetes mas recientes que los que se encuentran en los listados del repositorio.
Cuando esta establecido en
.BR 2 ,
todos los paquetes no actualizados son listados.
Cambiando
.B DEBUG_UPDATES
a
.B 1
o
.B 2
pude ser de utilidad si aparecen paquetes nuevos que pueden obviarse en una actualización.
.IP
La configuración por defecto es:
.IP
\fCDEBUG_UPDATES=${DEBUG_UPDATES:-0}\fP
.\"---------------------------------------------------------------------
.TP
.B DIFF
Comando.
.IP
Esta opción le permite al usuario establecer que programa usar cuando
.B sbopkg
muestra diferencias entre archivos editados.
.IP
La configuración por defecto es:
.IP
\fCDIFF=${DIFF:-diff}\fP
.\"---------------------------------------------------------------------
.TP
.B DIFFOPTS
Opciones de comando.
.IP
Esta opción le permite al usuario establecer que opciones serán usadas 
por el programa
.I $DIFF
cuando
.B sbopkg
muestre las diferencias entre los archivos editados.
.IP
La configuración por defecto es:
.IP
\fCDIFFOPTS=${DIFFOPTS:--u}\fP
.\"---------------------------------------------------------------------
.TP
.B KEEPLOG
Booleano.
.IP
Esta opción le permite al usuario escoger si mantener un bitácora (log) permanente 
de todos los paquetes que son construidos con
.B sbopkg
para volver a ver el historial de las construcciones o para la solucionar problemas.
Ver
.B LOGFILE
para la localizar de este bitácora.
.IP
La tarea por defecto es:
.IP
\fCKEEPLOG=${KEEPLOG:-YES}\fP
.\"---------------------------------------------------------------------
.TP
.B LOGFILE
Ruta.
.IP
Esta opción establece el nombre de la bitácora (log) de construcción si
.B KEEPLOG
esta establecido como
.BR YES .
.IP
La configuración por defecto es:
.IP
\fCLOGFILE=${LOGFILE:-/var/log/sbopkg/sbopkg-build-log}\fP
.\"---------------------------------------------------------------------
.TP
.B MKDIR_PROMPT
Booleano.
.IP
Cuando esta establecido como
.BR YES ,
.B sbopkg
le pedirá la confirmación antes de cambiar el sistema de archivos y crear
sus directorios.
Si no desea recibir la petición de confirmación (por ejemplo, si tiene 
parte de los directorios en sistemas de archivos temporales y no deseas 
recibir la petición de confirmación cada vez que el sistema de archivos 
es vuelto a iniciar) puedes establecerlo como
.BR NO .
.IP
La tarea por defecto es:
.IP
\fCMKDIR_PROMPT=${MKDIR_PROMPT:-YES}\fP
.\"---------------------------------------------------------------------
.TP
.B NICE
Intero.
.IP
este valor es pasado a
.BR nice (1)
como el argumento
.B \-n .
.\" I had to 'hardcode' the default here to explain things so, while the
.\" 'The default assignment is' will be automatically updated, remember
.\" to also change this text if we ever set the niceness to something
.\" other than nice's default. (Not that we will.)
Si este valor no esta configurado o se deja con el valor por defecto,
.B sbopkg
ejecutará el SlackBuild con el valor por defecto de
.BR nice , 
que es
.B 10.
Si no desea que la prioridad tenga efecto, asegúrese de configurar el valor a
.BR 0 .
Note que ésto solo afecta a la ejecución del SlackBuild y no afecta a la 
prioridad de
.B sbopkg
por completo.
.IP
La configuración por defecto es:
.IP
\fCNICE=${NICE:-10}\fP
.\"---------------------------------------------------------------------
.TP
.B OUTPUT
Ruta.
.IP
Esta opción establece el directorio por defecto donde los paquetes son compilados y guardados.
.B OUTPUT
debe ser exportado como si fuera usado por los SlackBuilds de SBo.
Cabe destacar que el valor por defecto de
.B OUTPUT
es el mismo que el utilizado en los SlackBuilds de SBo.
.IP
La configuración por defecto es:
.IP
\fCexport OUTPUT=${OUTPUT:-/tmp}\fP
.\"---------------------------------------------------------------------
.TP
.B QUEUEDIR
Ruta.
.IP
Esta opción define el directorio bajo el que los archivos de cola seran 
mantenidos.
.IP
La asignación por defecto es:
.IP
\fCQUEUEDIR=${QUEUEDIR:-/var/lib/sbopkg/queues}\fP
.\"---------------------------------------------------------------------
.TP
.B REPO_BRANCH
Enumeración.
.IP
Esta opción le permite al usuario establecer el principal repositorio activo 
por defecto.
Los valores estándar actuales son listados por defecto en los archivos
.I repos.d/*
y también pueden ser listados al publicarlos.
.RS
.IP
.nf
\fC# sbopkg -V ?\fP
.fi
.RE
.IP
La asignación por defecto es:
.IP
\fCREPO_BRANCH=${REPO_BRANCH:-13.1}\fP
.\"---------------------------------------------------------------------
.TP
.B REPO_NAME
Enumeración.
.IP
Esta opción le permite al usuario escoger que repositorio usar.
Ver
.B REPO_BRANCH
para saber como conseguir los valores estándar para ésta enumeración.
La opción "local" corresponde al un repositorio mantenido por el usuario, 
que debe tener la misma estructura que la que es usada por SBo, usando la jerarquía
.I category/package/files .
Nota: todas las variables
.B REPO_*
son afectadas por los archivos mantenidos en en los repositorios
.I /etc/sbopkg/repos.d.
Por favor vea el documento
.I README-repos
en el directorio de documentación de
.B sbopkg .
.IP
La asignación por defecto es:
.IP
\fCREPO_NAME=${REPO_NAME:-SBo}\fP
.\"---------------------------------------------------------------------
.TP
.B REPO_ROOT
Ruta.
.IP
Esta opción le permite al usuario establecer los espejos (mirrors) de los 
repositorios remotos.
Actualmente, el tamaño de una copia local del repositorio SBo es de alrededor de 250MB.
.IP
La asignación por defecto es:
.IP
\fCREPO_ROOT=${REPO_ROOT:-/var/lib/sbopkg}\fP
.\"---------------------------------------------------------------------
.TP
.B RSYNCFLAGS
Opciones del comando.
.IP
.B Rsync
es usado por
.B sbopkg
para crear un espejo (mirror) el repositorio SBo.
Esta opción permite al usuario ajustar manualmente las banderas (opciones) 
de
.B rsync
que seran usadas por
.BR sbopkg .
Los usuarios deben ser cautelosos al realizar cualquier cambio a los valores por 
defecto ya que nuevas banderas u opciones pueden o nó funcionar adecuadamente.
Nota: el comando
.B rsync
en
.B sbopkg
ya utiliza las banderas
.BR \-\-archive ,
.BR \-\-delete ,
.BR \-\-no-owner ,
y
.B \-\-exclude
así que no es necesario añadirlas a las opciones de
.B RSYNCFLAGS .
Cambiar las opciones internas por defecto no es recomendado.
Sin embargo,
.B \-\-timeout
es una opción útil para jugar si hay errores de sincronización.
.IP
La asignación por defecto es:
.IP
\fCRSYNCFLAGS="${RSYNCFLAGS:---verbose --timeout=30}"\fP
.\"---------------------------------------------------------------------
.TP
.B SBOPKGTMP
Ruta.
.IP
Esta opción establece el directorio por defecto donde algunos archivos 
especificos de
.B sbopkg
son guardados de forma temporal.
.IP
La asignación por defecto es:
.IP
\fCxxxSBOPKGTMPxxx\fP
.\"---------------------------------------------------------------------
.TP
.B SRCDIR
Ruta.
.IP
Esta opción contiene la localización del directorio de cache, donde las 
descargas de archivos fuente son guardados.
.IP
La asignación por defecto es:
.IP
\fCSRCDIR=${SRCDIR:-/var/cache/sbopkg}\fP
.\"---------------------------------------------------------------------
.TP
.B TMP
Ruta.
.IP
Esta opción establece el directorio por defecto donde los paquetes 
construidos son guradados.
.B TMP
debe ser exportado como lo és en los SlackBuilds de SBo.
Nótese que el valor por defecto de
.B TMP
es además el mismo que el de los SlackBuilds de SBo.
.IP
También nótese que si la variable
.B CLEANUP
esta establecida como
.BR YES ,
cualquier opción personalizada de
.B TMP
es ignorada.
.IP
La asignación por defecto es:
.IP
\fCexport TMP=${TMP:-/tmp/SBo}\fP
.\"---------------------------------------------------------------------
.TP
.B WGETFLAGS
Opciones de comando.
.IP
.B Wget
es usado por
.B sbopkg
para descargar los archivos fuentes y construir el paquete.
Esta opción permite al usuario ajustar las banderas (opciones) de
.B wget
que son usadas por
.BR sbopkg .
Los usuarios deben ser cautelosos al realizar cualquier cambio a los valores por 
defecto ya que nuevas banderas u opciones pueden o nó funcionar adecuadamente.
Sin embargo,
.B \-\-timeout
es una opción útil para jugar si hay errores de descarga.
.IP
La asignación por defecto es:
.IP
\fCWGETFLAGS="${WGETFLAGS:--c --progress=bar:force --timeout=30 --tries=5}"\fP
.\"=====================================================================
.SH NOTAS
.\"---------------------------------------------------------------------
.SS Sobreescribiendo Variables de Entorno
Es posible establecer o sobreescribir variables de entorno y pasarlas 
a los SlackBuilds cuando es construido sin
.BR sbopkg .
Ésto está demostrado en la siguiente línea de ejemplo (y otras como 
ella) en el archivo
.I sbopkg.conf :
.RS
.PP
.nf
\fCexport TMP=${TMP:-/tmp/SBo}\fP
.fi
.RE
.PP
Esto establece
.B TMP
a
.I /tmp/SBo
para construir los paquetes SBo sin 
.B sbopkg
(el cual es aun actualmente el predeterminado para los SlackBuilds de SBo).
Ya que ésta variable es exportada, puede cambiar a
.B sbopkg
y a los paquetes construidos de SBo sin
.BR sbopkg .
Por ejemplo, cambiar esta linea, por lo que siguiente:
.RS
.PP
.nf
\fCexport TMP=${TMP:-/home/sbo/tmp}\fP
.fi
.RE
.PP
entonces se establecerá
.B TMP
a
.I /home/sbo/tmp
para construir paquetes de SBo y también permitir la sobreescritura en 
tiempo de ejecución invocando
.B sbopkg
como
.RS
.PP
.nf
\fC# export TMP=foo; sbopkg\fP
.fi
.RE
.PP
.B OUTPUT
puede también cambiar el guardado de paquetes compilados en otra localización en lugar de la predeterminada
.IR /tmp .
.PP
También puedes exportar variables en
.I sbopkg.conf
que no son usadas por
.B sbopkg .
.\"---------------------------------------------------------------------
.SS Sobre la variable ARCH
Quiza te preguntes porque
.B ARCH
no es una opción de configuración por defecto en el archivo
.I sbopkg.conf .
La razón es que no lo tiene que serlo.
Si
.B ARCH
no esta establecida,
.B sbopkg
hace una comprobación (utilizando la salida de
.BR "uname \-m" )
para determinar que arquitectura de sistema es.
Si la arquitectura es x86, x86_64, o arm*, entonces
.B sbopkg
automáticamente establecerá
.B ARCH
a i486, x86_64, o arm, respectivamente.
Si
.B ARCH
esta establecida,
.B sbopkg
heredara esa configuración.
Esto significa que cada usuario puede añadir, por ejemplo,
.B export ARCH=i686
en su
.I .bashrc
o archivo similar, u otro usuario puede también ejecutar algo 
como si pareciera la terminal de root
.RS
.PP
.nf
\fC# export ARCH=i686; sbopkg\fP
.fi
.RE
.PP
El usuario puede también añadir manualmente su archivo
.I sbopkg.conf
si desea.
Finalmente, si
.B ARCH
no esta establecida por el usuario y
.B sbopkg
no detectara una de las arquitecturas previamente mencionadas, entonces
.B ARCH
sera establecida por cualquiera que este en los SlackBuilds.
Nótese que un SlackBuild puede, en algunas ocasiones, descartar o 
sobreescribir las anteriores configuraciones de
.B ARCH
si es requerido para la construcción del paquete.
.\"=====================================================================
.SH ARCHIVOS
.TP 3
.I /etc/sbopkg/sbopkg.conf
Archivo que especifica opciones de configuración.
.TP
.I ~/.sbopkg.conf
Archivo que sobreescribe las opciones del sistema.
.TP
.I /etc/sbopkg/renames.d/*.renames
Archivo por defecto que lista software en el repositorio SBo que ha sido
renombrado.
Ver el documento
.I README-renames
en el directorio de documentación de
.B sbopkg
para mas información.
.TP
.I /etc/sbopkg/repos.d/*.repo
Archivos para varios tipos de repositorios de
.B sbopkg .
Ver el documento
.I README-repos
en el directorio de documentación de
.B sbopkg
para mas información.
.\"=====================================================================
.SH AUTORES
Willy Sudiarto Raharjo
<willysr@sbopkg.org>

Chess Griffin
<chess@chessgriffin.com>
.PP
Mauro Giachero
<mauro.giachero@gmail.com>
.PP
slakmagik
<slakmagik@gmail.com>
.\"=====================================================================
.\" Make the release process handle a DOCDIR here? But the files from
.\" the official tarball go here.
.SH SEE ALSO
.BR diff (1),
.BR rsync (1),
.BR sbopkg (8),
.BR uname (1),
.BR wget (1),
.IR /usr/doc/sbopkg-xxxVERSIONxxx/*
.SH TRADUCCION
Esta traducción ha sido realizada por Pablo Castaño Fernández 
<waruto@hurricane-project.org> el 17 de Enero de 2011.
.PP
Actualizado por Dhaby Xiloj <slack.dhabyx@gmail.com> el 06 de Enero de 2016.
.\" vim:set tw=72:
