#!/bin/bash

. /usr/share/sbopkg/sqg/functions

REPO_DIR="$1"
QUEUEDIR="$2"
INFO="$3"

. $INFO
if [[ ! -z $REQUIRES || $SKIP_EMPTY == "NO" ]]; then
  build_queuefile "$REPO_DIR" "$QUEUEDIR" "$PRGNAM"
fi
